#ifndef BRH_CPP_ALLOCATORS_SRC_BRIDGERRHOLT_ALLOCATORS_MULTITHREAD_THREAD_H
#define BRH_CPP_ALLOCATORS_SRC_BRIDGERRHOLT_ALLOCATORS_MULTITHREAD_THREAD_H

#define BRH_CPP_ALLOCATORS_MULTITHREADED

#ifdef BRH_CPP_ALLOCATORS_MULTITHREADED
	#include <thread>
	#include <mutex>
#endif

#endif
